version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
  exclusions:
    rules:
      # Test files can be more lenient about error checking
      - path: _test\.go
        linters:
          - errcheck
