# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: shiftlog

before:
  hooks:
    - go mod tidy

builds:
  - id: shiftlog
    binary: shiftlog
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/re-cinq/shift-log/cmd.version={{.Version}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: re-cinq
    name: shift-log
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
