package opencode

import (
	"fmt"
	"os"
	"path/filepath"
)

// pluginTemplate is the JavaScript plugin that hooks into OpenCode's
// tool execution hooks and calls shiftlog store after git commits.
//
// OpenCode plugin hooks:
//
//	tool.execute.before(input, output) — input: {tool, sessionID, callID}, output: {args}
//	tool.execute.after(input, output)  — input: {tool, sessionID, callID}, output: {title, output, metadata}
//
// The command string is only available in the "before" hook (via output.args),
// so we capture it there and act on it in the "after" hook, matching by callID.
//
// Compatibility notes for OpenCode v1.17+:
//   - input.tool may be an object in newer versions; we coerce it to a string
//   - input.sessionID may vary; we coerce to string and handle undefined
//   - directory may not always be the git project root; we detect the git root explicitly
const pluginTemplate = `// shiftlog plugin for OpenCode CLI
// Auto-generated by shiftlog init --agent=opencode
// Do not edit manually - re-run 'shiftlog init --agent=opencode' to update

export const ShiftlogPlugin = async ({ directory, client }) => {
  const pendingCommits = new Map();

  // Resolve the git project root. In OpenCode v1.x 'directory' is the project
  // dir; newer versions may pass a different path. We validate via git and fall
  // back to process.cwd() so the store command always runs inside a git repo.
  const resolveProjectDir = async () => {
    const { execSync } = await import("child_process");
    for (const cwd of [directory, process.cwd()]) {
      if (!cwd) continue;
      try {
        const root = execSync("git rev-parse --show-toplevel", {
          cwd,
          encoding: "utf8",
          stdio: ["ignore", "pipe", "ignore"],
          timeout: 5000,
        }).trim();
        if (root) return root;
      } catch (e) {}
    }
    return directory || process.cwd();
  };

  // Coerce a value that may be a string, object, or undefined to a plain string.
  const toStr = (v) => {
    if (typeof v === "string") return v;
    if (v == null) return "";
    if (typeof v === "object") return v.name || v.type || v.id || "";
    return String(v);
  };

  return {
    "tool.execute.before": async (input, output) => {
      const command = output?.args?.command || output?.args?.cmd || "";
      if (command.includes("git commit") || command.includes("git-commit")) {
        pendingCommits.set(input.callID, {
          command,
          tool: toStr(input.tool),
          sessionID: toStr(input.sessionID),
        });
      }
    },

    "tool.execute.after": async (input, output) => {
      const pending = pendingCommits.get(input.callID);
      if (!pending) return;
      pendingCommits.delete(input.callID);

      // Try to fetch messages via the SDK client API
      let transcriptData = "";
      if (client && pending.sessionID) {
        try {
          const msgs = await client.session.messages({ path: { id: pending.sessionID } });
          if (msgs && Array.isArray(msgs)) {
            transcriptData = JSON.stringify(msgs.map(m => ({
              role: m.role || "",
              id: m.id || "",
              content: m.content || "",
              time: m.time || {},
            })));
          }
        } catch (e) {
          // Fall back to data_dir approach below
        }
      }

      const dataDir = process.platform === "darwin"
          ? process.env.HOME + "/Library/Application Support/opencode"
          : (process.env.XDG_DATA_HOME || process.env.HOME + "/.local/share") + "/opencode";

      const hookData = JSON.stringify({
        session_id: pending.sessionID || "",
        data_dir: dataDir,
        project_dir: directory || "",
        tool_name: pending.tool || "",
        tool_input: { command: pending.command },
        ...(transcriptData ? { transcript_data: transcriptData } : {}),
      });

      try {
        const { execSync } = await import("child_process");
        const projectDir = await resolveProjectDir();
        execSync("shiftlog store --agent=opencode", {
          input: hookData,
          cwd: projectDir,
          timeout: 30000,
          stdio: ["pipe", "pipe", "pipe"],
        });
      } catch (e) {
        // Silently ignore errors to not disrupt workflow
      }
    },
  };
};
`

// InstallPlugin writes the shiftlog plugin to .opencode/plugins/shiftlog.js.
func InstallPlugin(repoRoot string) error {
	pluginDir := filepath.Join(repoRoot, ".opencode", "plugins")
	if err := os.MkdirAll(pluginDir, 0755); err != nil {
		return fmt.Errorf("could not create plugin directory: %w", err)
	}

	pluginPath := filepath.Join(pluginDir, "shiftlog.js")
	if err := os.WriteFile(pluginPath, []byte(pluginTemplate), 0644); err != nil {
		return fmt.Errorf("could not write plugin file: %w", err)
	}

	return nil
}

// RemovePlugin removes the shiftlog plugin file.
// Also removes the plugins directory if it's empty afterward.
func RemovePlugin(repoRoot string) error {
	pluginPath := filepath.Join(repoRoot, ".opencode", "plugins", "shiftlog.js")
	if err := os.Remove(pluginPath); err != nil && !os.IsNotExist(err) {
		return err
	}

	// Remove plugins dir if empty
	pluginDir := filepath.Join(repoRoot, ".opencode", "plugins")
	entries, err := os.ReadDir(pluginDir)
	if err == nil && len(entries) == 0 {
		_ = os.Remove(pluginDir)
	}

	return nil
}

// HasPlugin checks if the shiftlog plugin is installed.
func HasPlugin(repoRoot string) bool {
	pluginPath := filepath.Join(repoRoot, ".opencode", "plugins", "shiftlog.js")
	_, err := os.Stat(pluginPath)
	return err == nil
}
